Config option to enable/disable dropping players on first join (fixes #11)
MLG-Fortress/PopulationDensity pull request #12
Opened 2017-02-28 19:12 UTC by zedwick

~ PopulationDensity.LaunchAndDropPlayers config option only controls dropping players when travelling between region posts

+ PopulationDensity.LaunchAndDropNewPlayers config option controls dropping players on their first join to the server (I realise players are never launched on first join, but keeping the names similar to aid when configuring)

2017-02-28 20:36 UTC, RoboMWM requested changes
Seems ok, took me an extra couple minutes to figure out how you were doing it lol.

However, can you fix the mixing of tabs/spaces?

2017-02-28 21:35 UTC, zedwick commented
I think I got them all...

2017-03-01 01:22 UTC, RoboMWM approved these changes

2017-03-01 01:23 UTC, RoboMWM commented
Still don't like the extra whitespace between the parenthesis though lol, but it will do. Will pull when I can compile and upload the new update.

2017-03-01 11:49 UTC, zedwick commented
There you go :P

2017-03-01 15:08 UTC, merged