Added config option to disable teleporting nearby animals
MLG-Fortress/PopulationDensity pull request #19
Opened 2017-04-19 22:02 UTC by bittiez

Also fixed a few deprecated methods

2017-04-19 22:03 UTC, bittiez commented
Fixes #14

2017-04-20 03:23 UTC, RoboMWM requested changes
See comments. The majority of this PR changes the code style, making it inconsistent with the rest of this project.

2017-04-20 03:23 UTC, RoboMWM commented on pom.xml
> +    <version>5.11</version>
Don't change version in PRs. I'll change it when I make a release.

2017-04-20 03:23 UTC, RoboMWM commented on src/me/ryanhamshire/PopulationDensity/PlayerEventHandler.java
> +	public PlayerEventHandler(DataStore dataStore, PopulationDensity plugin, boolean teleportNearbyAnimals) {
Um... this is not a good idea for any config option.

2017-04-20 03:23 UTC, RoboMWM commented on src/me/ryanhamshire/PopulationDensity/PopulationDensity.java
> +            Player invitee = findPlayerByName(args[0]);
This isn't deprecated anymore. Doesn't matter anyways - the reason it was "deprecated" in the first place was to discourage plugin makers from storing data with player names and to use UUIDs instead.

Please revert this change entirely. You may change this to `getPlayerExact` if you wish

2017-04-20 03:23 UTC, RoboMWM commented on src/me/ryanhamshire/PopulationDensity/TeleportPlayerTask.java
> +import org.bukkit.entity.*;
Please change your IDE settings to _not_ do this. (and try to undo accordingly, thanks).

2017-04-20 03:23 UTC, RoboMWM commented on src/me/ryanhamshire/PopulationDensity/TeleportPlayerTask.java
> +                                entitiesToTeleport.add(entity);
What happened to all the newlines?

2017-04-20 15:34 UTC, FrankHeijden commented
So... is it fixed? Where can i download the fixed file?

2017-04-20 15:55 UTC, bittiez commented
My pull request wasn't accepted, I will try to get you my jar later when I'm not at work, until I can redo this per robo request

2017-04-20 16:24 UTC, FrankHeijden commented
ok, thanks :D

2017-04-20 19:50 UTC, bittiez commented
http://www.mediafire.com/file/1fo2ap1cqfd7wyd/PopulationDensity.jar

I'll make a new PR when I make the changes you preferred @RoboMWM

2017-04-20 19:50 UTC, closed without merging

2017-04-22 21:00 UTC, FrankHeijden commented
Hmm they do still teleport with players :(, first i thought it worked but now are players saying that it isnt anymore

2017-07-17 21:14 UTC, FrankHeijden commented
Btw, why is the file of the mediafire link 2.5MB, and the normal plugin just 72KB xD

2018-06-13 05:27 UTC, RoboMWM commented on src/me/ryanhamshire/PopulationDensity/PlayerEventHandler.java
> +	public PlayerEventHandler(DataStore dataStore, PopulationDensity plugin, boolean teleportNearbyAnimals) {
> this is not a good idea

Or rather, this does not follow the conventions of the rest of this plugin afaik

2018-06-13 05:29 UTC, RoboMWM commented
> My pull request wasn't accepted,

FYI, I simply requested changes, I didn't just flat-out reject it. Also, you should preferably separate each feature/change in individual PRs instead of lumping them altogether.

> Btw, why is the file of the mediafire link 2.5MB, and the normal plugin just 72KB xD

He probably didn't compile with maven and instead included dependencies or something of that nature.